{
AddonsPath: ../Addons/,
LogPath: ../Logs/,
PrintLogText: True,
LogBufferLength: 10,
LogFileLinesBeforeSplit: 10000,
gzipLogs: True,
ZKHost: 127.0.0.1:2181,
DatabaseUsername: bgUser,
DatabasePassword: 123456,
DatabaseHost: 127.0.0.1,
DatabaseName: bgdb
}
