{
AddonsPath: ../Addons/,
LogPath: ../Logs/,
PrintLogText: True,
LogBufferLength: 10,
LogFileLinesBeforeSplit: 10000,
gzipLogs: True,
ZKHost: 10.0.4.3,
ZKPort: 2181,
KafkaHost: 127.0.0.1,
KafkaPort: 9092,
DatabaseUsername: bgUser,
DatabasePassword: 123456,
DatabaseHost: 127.0.0.1,
DatabaseName: bgdb
}
