### DATABASE CONFIGURATION ###
DatabaseUsername: bgUser # Set the mysql database username
DatabasePassword: 123456 # Set the mysql database password
DatabaseHost: 10.1.4.2 # Set the mysql server host
DatabaseName: bgdb # Set the name of the database 


# Set Socket Params Here #
SocketBindAddress: 0.0.0.0, # Bind To All Addresses By Default
Protocol: TCP # Only supports TCP for now, changing this doesn't do anything
Port : 6598 # Set the port number to be used by the APIServer


#### APACHE KAFKA CONFIGURATION ###
KafkaHost: localhost # Set the address of the server running the kafka broker, default is localhost
KafkaPort: 9092 # Set the port to connect to the kafka broker, default is 9092


### ZOOKEEPER CONFIGURATION ###
ZKHost: 127.0.0.1 # Set the host running the zookeeper server, default is localhost
ZKPort: 2181 # Set port used to connect to the zookeeper server, default is 2181


### LOGGER CONFIGURATION ###
LogPath: ../Logs/ # Set The Path For Logs
PrintLogText: True # Enable or Disable Printing Logs
SecondsToKeepLogs: 100000  # Define The Number Of Seconds To Keep Logs
ConsoleOutputEnabled: True # Enable or disable console output
ConsoleColorEnabled: True # Enable or disable console color output

# Set The Colors For Various Log Levels #
LogLevelColors:
    0: [255,255,255]
    1: [77,166,255]
    2: [179,255,217]
    3: [181,121,255]
    4: [212,0,255]
    5: [106,255,77]
    6: [204,153,0]
    7: [149,179,0]
    8: [255,255,0]
    9: [255,170,0]
    10: [255,0,0]

# Set Name For Log Strings #
LogLevelNames:
    0: System
    1: Config
    2: Audit
    3: Info
    4: Detail
    5: Fine
    6: Finer
    7: Finest
    8: Warning
    9: Severe
    10: Fatal





